#!/usr/bin/env sh
# Back up the annotation database and the audio volume.
#
# The corrected annotations are the most expensive artifact this project
# produces: tens of hours of human judgement that cannot be regenerated by
# re-running anything. Losing the Postgres volume loses all of it. Run this on
# a schedule from the host, not from inside a container.
#
#   sh server/scripts/backup.sh              # -> ./backups/
#   BACKUP_DIR=/mnt/nas/adg sh .../backup.sh
#   KEEP_DAYS=60 sh server/scripts/backup.sh
#
# Restore:
#   docker compose exec -T db pg_restore -U adg -d adg --clean < backups/db-....dump
#   docker run --rm -v tool-03-audiolabelgenerate_appdata:/data -v "$PWD/backups":/b \
#     alpine tar xzf /b/data-....tar.gz -C /
#
# Note that `GET /api/export/rttm.zip` is a third, human-readable line of
# defence: plain text, no database needed to read it. It is not a substitute
# for this script (it omits audio and in-progress work) but it is the copy
# that will still be usable in five years.

set -eu

BACKUP_DIR="${BACKUP_DIR:-./backups}"
KEEP_DAYS="${KEEP_DAYS:-30}"
STAMP="$(date +%Y%m%d-%H%M%S)"

mkdir -p "$BACKUP_DIR"

echo "==> database"
# -Fc is the custom format: compressed and restorable table-by-table.
docker compose exec -T db pg_dump -U adg -d adg -Fc > "$BACKUP_DIR/db-$STAMP.dump"
echo "    $BACKUP_DIR/db-$STAMP.dump"

echo "==> audio + peaks volume"
# Read the named volume through a throwaway container: the host has no direct
# path to it, and stopping the api to copy files would be worse.
# The authoritative name comes from the RUNNING api container's own mount.
# `compose config` cannot answer this: it prints the symbolic source
# ("appdata"), and deriving the name by sanitising the directory loses the
# hyphens -- which picks up a stale empty volume from an older compose
# version if one happens to exist. (Both bit us.)
CID="$(docker compose ps -q api 2>/dev/null | head -n1)"
VOLUME=""
if [ -n "$CID" ]; then
  VOLUME="$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/data"}}{{.Name}}{{end}}{{end}}' "$CID" 2>/dev/null)"
fi
if [ -z "$VOLUME" ]; then
  VOLUME="$(basename "$PWD" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')_appdata"
fi

# The host side of the bind mount, in the form docker accepts:
#   POSIX on Linux/macOS, Windows under Git Bash (where `pwd -W` prints it in
#   `D:/...` form). Under MSYS, MSYS2 rewrites EVERY POSIX-looking piece of a
#   -v argument -- "/backup" alone becomes "$MSYS_ROOT/backup" -- which is why
#   the container side has to be protected with MSYS_NO_PATHCONV=1.
case "$(uname -s 2>/dev/null)" in
  MINGW*|MSYS*|CYGWIN*)
    HOST_BACKUP="$(cd "$BACKUP_DIR" && pwd -W)"
    export MSYS_NO_PATHCONV=1
    ;;
  *)
    HOST_BACKUP="$(cd "$BACKUP_DIR" && pwd -P)"
    ;;
esac

docker run --rm \
  -v "$VOLUME":/data:ro \
  -v "$HOST_BACKUP":/backup \
  alpine tar czf "/backup/data-$STAMP.tar.gz" -C /data .
echo "    $BACKUP_DIR/data-$STAMP.tar.gz"

echo "==> pruning backups older than $KEEP_DAYS days"
find "$BACKUP_DIR" -name 'db-*.dump' -mtime "+$KEEP_DAYS" -print -delete
find "$BACKUP_DIR" -name 'data-*.tar.gz' -mtime "+$KEEP_DAYS" -print -delete

echo "done."
