"""Baseline: the DDL the database was born with.

Statement-for-statement transcription of ``server/app/schema.sql``, which is
retired in the same change. Deliberately ``CREATE ... IF NOT EXISTS``
everywhere: databases created by the old startup bootstrap must converge under
``upgrade head`` without any object being re-created or any data touched --
the live database holds hand-corrected annotations that cannot be
reproduced. Fresh databases land on exactly the same schema.

"Statuses are TEXT + CHECK" is preserved as-is: adding a value to a CHECK is
an ordinary ALTER, adding one to an ENUM is a migration ritual.

The FIRST schema change after this baseline is a normal, non-idempotent,
autogenerated revision (``alembic revision --autogenerate -m "..."``); this
file stays frozen because it is the floor every database upgrades from.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-05
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # One statement per op.execute: psycopg only accepts multi-statement
    # strings through the simple query protocol, and a per-statement listing
    # reads like the CREATE sequence it replaces.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name       TEXT NOT NULL UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS recordings (
            id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            -- Doubles as the RTTM file id, so it must survive sanitize_uri().
            session_name       TEXT NOT NULL UNIQUE,
            original_name      TEXT NOT NULL,
            -- Hash of the bytes as uploaded, before normalization.
            sha256             CHAR(64) NOT NULL UNIQUE,
            -- Measured from the normalized wav, which is also what is served.
            duration_sec       DOUBLE PRECISION NOT NULL,
            status             TEXT NOT NULL DEFAULT 'uploaded',
            claimed_by         UUID REFERENCES users(id),
            claimed_at         TIMESTAMPTZ,
            -- Optimistic lock for the whole-annotation PUT.
            annotation_version INTEGER NOT NULL DEFAULT 0,
            last_edited_by     UUID REFERENCES users(id),
            error              TEXT,
            created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT recordings_status_check CHECK (status IN (
                'uploaded', 'queued', 'running', 'ready', 'annotating',
                'done', 'failed'
            )),
            CONSTRAINT recordings_duration_check CHECK (duration_sec > 0)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_recordings_status"
        " ON recordings (status)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_recordings_claimed_by"
        " ON recordings (claimed_by) WHERE claimed_by IS NOT NULL"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS speakers (
            recording_id UUID NOT NULL REFERENCES recordings(id)
                ON DELETE CASCADE,
            -- Stable opaque key, never rewritten. Renames touch `name` only.
            label        TEXT NOT NULL,
            name         TEXT NOT NULL,
            color        TEXT NOT NULL DEFAULT '#1890ff',
            sort_order   INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (recording_id, label)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS segments (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            recording_id  UUID NOT NULL REFERENCES recordings(id)
                ON DELETE CASCADE,
            speaker_label TEXT NOT NULL,
            start_sec     DOUBLE PRECISION NOT NULL,
            end_sec       DOUBLE PRECISION NOT NULL,
            -- Phase 2 (subtitles). Never reaches RTTM: see app/rttm.py.
            text          TEXT NOT NULL DEFAULT '',
            -- Reference-audio designation for speaker verification.
            is_stable     BOOLEAN NOT NULL DEFAULT FALSE,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT segments_start_check CHECK (start_sec >= 0),
            CONSTRAINT segments_order_check CHECK (end_sec > start_sec),
            FOREIGN KEY (recording_id, speaker_label)
                REFERENCES speakers (recording_id, label) ON DELETE CASCADE
        )
        """
    )
    # Databases that predate the column: CREATE IF NOT EXISTS cannot add it.
    op.execute(
        "ALTER TABLE segments ADD COLUMN IF NOT EXISTS is_stable"
        " BOOLEAN NOT NULL DEFAULT FALSE"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS segment_embeddings (
            recording_id UUID NOT NULL REFERENCES recordings(id)
                ON DELETE CASCADE,
            start_sec    DOUBLE PRECISION NOT NULL,
            end_sec      DOUBLE PRECISION NOT NULL,
            model_id     TEXT NOT NULL,
            embedding    JSONB NOT NULL,
            computed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (recording_id, start_sec, end_sec)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_segments_recording"
        " ON segments (recording_id, start_sec)"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jobs (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            recording_id UUID NOT NULL REFERENCES recordings(id)
                ON DELETE CASCADE,
            status       TEXT NOT NULL DEFAULT 'queued',
            worker_id    TEXT,
            -- Incremented only when a stale job is re-claimed, so a first run
            -- does not consume an attempt.
            attempts     INTEGER NOT NULL DEFAULT 0,
            claimed_at   TIMESTAMPTZ,
            heartbeat_at TIMESTAMPTZ,
            error        TEXT,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at  TIMESTAMPTZ,
            CONSTRAINT jobs_status_check CHECK (status IN (
                'queued', 'running', 'succeeded', 'failed'
            ))
        )
        """
    )
    # One active job per recording, enforced by the database rather than by a
    # check-then-insert race in application code.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_active"
        " ON jobs (recording_id) WHERE status IN ('queued', 'running')"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_jobs_claimable"
        " ON jobs (status, created_at)"
    )


def downgrade() -> None:
    # Baseline convenience only: drops everything, reverse order.
    op.execute("DROP INDEX IF EXISTS ix_jobs_claimable")
    op.execute("DROP INDEX IF EXISTS uq_jobs_active")
    op.execute("DROP TABLE IF EXISTS jobs")
    op.execute("DROP INDEX IF EXISTS ix_segments_recording")
    op.execute("DROP TABLE IF EXISTS segment_embeddings")
    op.execute("DROP TABLE IF EXISTS segments")
    op.execute("DROP TABLE IF EXISTS speakers")
    op.execute("DROP INDEX IF EXISTS ix_recordings_claimed_by")
    op.execute("DROP INDEX IF EXISTS ix_recordings_status")
    op.execute("DROP TABLE IF EXISTS recordings")
    op.execute("DROP TABLE IF EXISTS users")
