"""Alembic is the schema authority: models and database must agree.

``init_schema()`` (called below and from every container's startup) brings
the database to ``head``. ``alembic check`` then fails the moment
``app/models.py`` and the database drift -- in either direction.

The test database is itself a legacy database (its tables were created by the
old schema.sql bootstrap, and fixtures reapply init_schema session-wide), so
passing this module is also the proof that the idempotent baseline converges
a pre-Alembic database. The fresh-database path is exercised against the
adg_mig scratch database when this baseline was authored; future schema
changes should add a per-change test rather than a second full-database one.

When a models.py edit makes this test fail, the fix is:

    cd server && alembic revision --autogenerate -m "describe change"
    #   then upgrade (or let the next container start) and test the change.

It is NOT to edit a database by hand.
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.util import AutogenerateDiffsDetected

from app.db import alembic_config, init_schema  # noqa: E402


@pytest.fixture(scope="session", autouse=True)
def _schema():
    init_schema()


def test_models_and_database_agree():
    try:
        command.check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"models.py and the database drifted -- is a revision missing?\n{exc}", pytrace=False)


def test_init_schema_is_idempotent():
    # Container startups race: every process runs init_schema, twice on every
    # restart. Running it again must stay a no-op at head, never an error.
    init_schema()
    init_schema()
